version: '3'

services:
  strapi:
    build:
      context: strapi  # Le chemin vers le dossier contenant le Dockerfile de Strapi
    ports:
      - "1337:1337"  # Assurez-vous que le port d'exposition correspond à celui défini dans le Dockerfile de Strapi

  eleventy:
    build:
      context: frontend  # Le chemin vers le dossier contenant le Dockerfile d'Eleventy
    ports:
      - "8080:8080"  # Assurez-vous que le port d'exposition correspond à celui défini dans le Dockerfile d'Eleventy
    depends_on:
      - strapi  # Indique que Eleventy dépend de Strapi pour démarrer
